### ISSUE TITLE
Support username password login.

### ISSUE THREAD

**Issue by doggie1989** [jcabi/jcabi-ssh#21] opened 2015-04-16 12:37 UTC

**Comment by dmarkov** [comment] 2015-05-05 07:16
@doggie1989 I will ask someone to take care of this task soon

**Comment by doggie1989** [comment] 2015-05-22 08:38
@dmarkov  

Firstly,Thank you very much.
Any further information about this issue?

**Comment by dmarkov** [comment] 2015-06-18 09:37
@suseika could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by Suseika** [comment] 2015-06-18 12:52
@yegor256 Am I allowed to change the existing API? In order to implement this task, I would like to redesign calls to `new SSH(host, port, user, key);` to be `new SSHWithPasswd(host, port, user, password)` and `new SSHWithKey(host, port, user, key)`. Otherwise there is no clean way to add the functionality required by this issue.

**Comment by yegor256** [comment] 2015-06-18 17:43
@Suseika let's leave the current class named as `SSH` and create a new one `SSHByPassword`

**Comment by Suseika** [comment] 2015-06-18 19:44
@yegor256 Okay.

**Comment by Suseika** [comment] 2015-06-20 07:48
@dmarkov Please review #25

**Comment by dmarkov** [comment] 2015-06-22 07:13
> @dmarkov Please review #25 

@suseika I will take a look, thanks

**Comment by Suseika** [comment] 2015-06-24 16:27
@doggie1989 Hey, I implemented login with password in #25, please see and close the issue if you're satisfied with the implementation.

**Comment by dmarkov** [comment] 2015-06-25 07:58
@rultor @doggie1989 please take a look, rultor closed it automatically

**Comment by dmarkov** [comment] 2015-06-26 12:23
@doggie1989 3 puzzles were created here: `21-74327cdd`/#27, `21-5047b140`, `21-40f93421`

**Comment by doggie1989** [comment] 2015-06-27 20:18
Hi guys, I will test it very soon.

**Comment by Suseika** [comment] 2015-07-02 11:09
@doggie1989 Are you going to test the feature?

**Comment by dmarkov** [comment] 2015-07-03 12:09
@suseika this task is in your hands for 15 days already; -30 to your rating, your total score is [+248](http://www.netbout.com/b/35381?open=rating)

**Comment by Suseika** [comment] 2015-07-03 13:01
@dmarkov What am I supposed to do if the author of the issue isn't going to accept the solution and close the task? I reported that I implemented what had to be implemented, he replied that he'll test very soon and then he disappeared. What did I do wrong?

**Comment by Suseika** [comment] 2015-07-03 16:56
@yegor256 The author of the task seems to have lost interest in it. It is implemented in #25 and merged, can you close this issue?

**Comment by yegor256** [comment] 2015-07-03 16:58
@rultor release, tag is `1.5`

**Comment by yegor256** [comment] 2015-07-03 16:58
@Suseika sure, thanks!

**Comment by Suseika** [comment] 2015-07-03 16:58
@dmarkov I'm done here.
@yegor256 Thanks.

**Comment by doggie1989** [comment] 2015-07-03 16:59
function is ok now. tested.

**Comment by yegor256** [comment] 2015-07-03 20:23
@doggie1989 @Suseika thanks all!

**Comment by dmarkov** [comment] 2015-07-06 07:11
@yegor256 only @doggie1989 can close this issue, since he opened it

**Comment by Suseika** [comment] 2015-07-06 14:16
@doggie1989 Sorry, we have some issues here. Please close this task manually once again.

**Comment by Suseika** [comment] 2015-07-06 14:16
@dmarkov I need more time here.

**Comment by yegor256** [comment] 2015-07-06 22:54
@dmarkov close it pls

**Comment by dmarkov** [comment] 2015-07-07 08:17
> @dmarkov I need more time here.

@suseika right, take your time and thanks for informing

**Comment by dmarkov** [comment] 2015-07-07 08:17
> @dmarkov close it pls

@yegor256 issue closes as you just asked

**Closed by dmarkov** 2015-07-07 08:17 UTC
Labels: 30 mins, @suseika, bug, DEV, enhancement

**Comment by Suseika** [comment] 2015-07-07 09:25
@dmarkov In case this information has been lost in this long conversation, the task has been solved by me in #25. Please pay.

**Comment by dmarkov** [comment] 2015-07-08 10:11
@suseika Many thanks! **30 mins** were added to your account in Transaction ID `AP-623488186N336464K` (task took 455 hours and 53 mins)... added +30 to your rating, now it is equal to [+323](http://www.netbout.com/b/35381?open=rating)

**Comment by dmarkov** [comment] 2016-04-12 07:45
@doggie1989 the last puzzle `21-40f93421`/#29 originated from here solved
